#!/bin/sh
#
# Startup script for the RaspCar Web Server
#
# chkconfig: – 85 15
# description: RaspCar
# processname: python
# pidfile: /tmp/pid

case "$1" in
start)
# Starts the lighttpd deamon
echo "Starting RaspberryCar Services"
python /Server/index.py
mjpg_streamer -i "/usr/lib/input_uvc.so -d /dev/video0  -r 640x480 -f 15" -o "/usr/lib/output_http.so -p 8090 -w /var/www/mjpg_streamer"

;;
stop)
# stops the daemon bt cat’ing the pidfile
echo "Stopping RaspberryCar"
kill -9 `cat /tmp/pid`i
;;
restart)
echo "Restarting RaspberryCar"
$0 stop
$0 start
;;
reload)
;;
*)
echo "Usage: raspCar (start|stop|restart|reload)"
exit 1
;;
esac
